### ISSUE TITLE
Maybe we should do some optimizations.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonicwww2#3]
<img width="847" alt="Screenshot 2022-06-22 at 07 46 57" src="https://user-images.githubusercontent.com/1024972/174952985-e13f0378-3074-489c-b674-3dca6c7b98e2.png">

**Comment by mworrell** [comment]
I will check some media classes, the images seem to be served lossless...

<img width="1026" alt="Screenshot 2022-06-22 at 08 14 33" src="https://user-images.githubusercontent.com/38268/174956613-19bc95c2-5de3-4fa3-933e-262ec166c81d.png">

**Comment by mworrell** [comment]
Slightly better now:

<img width="825" alt="Screenshot 2022-06-22 at 08 36 03" src="https://user-images.githubusercontent.com/38268/174959939-2f3cadb2-7cb5-4461-a789-f4786f6ed4f6.png">

**Comment by mworrell** [comment]
Removed the lossless, removed the videos from home, added srcset.

**Comment by mworrell** [comment]
Performance goes a bit up & down, but this might be good enough for now:

<img width="548" alt="Screenshot 2022-06-22 at 08 56 56" src="https://user-images.githubusercontent.com/38268/174964049-4891b74d-110f-4afc-bf2f-79ca5c6e3e55.png">

**Comment by mmzeeman** [comment]
Yes indeed.... Nice to have those media classes so it can be easily fixed.
